version: '3.7'

services:
  base-app:
    build:
      context: ..
      args:
        - PORT=${PORT}
      dockerfile: ./Dockerfile
      target: prod
    image: ${IMAGE_NAME}:prod
    container_name: ${IMAGE_NAME}
    restart: always
    depends_on:
      - db
    env_file:
      - ../.env
    environment:
      - TZ=${TZ}
      # - WAIT_HOSTS=db:3306
    ports:
      - ${EXTERNAL_PORT}:${PORT}

networks:
  default:
    name: ${IMAGE_NAME}-network
