version: '3.7'

services:
  nlw-esports:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ${IMAGE_NAME}:prod
    container_name: ${IMAGE_NAME}
    restart: always
    env_file:
      - ./.env
    environment:
      - TZ=${TZ}
    ports:
      - ${EXTERNAL_PORT}:${PORT}

networks:
  default:
    name: ${IMAGE_NAME}-network
